### ISSUE TITLE
IWR6843ISK-ODS相关

### ISSUE THREAD

**Issue by yishengsjh** [JUSTWILLPOWER/iwr6843isk-HARbag#1]
您好，我们手里有块IWR6843ISK-ODS板子，我们烧录并启动了和您相同的bin文件与lanuch文件，但是我们在ROS中观察到的点云效果非常差，杂点很多以至于肉眼都无法区分出哪一团点云是属于我们的。所以我想请问下您有没有遇到过与我们类似的问题？

**Comment by JUSTWILLPOWER** [comment]
你好，我还没有遇到这个问题，你们这个问题很有可能是由于板子配置的问题，在cfg目录下面有配置信息，你们可以先用网页版本https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/3.5.0/ 测试配置，然后导出
